### ISSUE TITLE
Lot's of noticeable noise looking like apperaing/disappearing circular nad blurred blobs.

### ISSUE THREAD

**Issue by michax** [NVIDIAGameWorks/RTXGI-DDGI#10]
In main example i can see quite a lot of strange noise when i increase light power or increase exposure. 
![sp2](https://user-images.githubusercontent.com/117785/80288735-3711fc80-873a-11ea-84c1-ce2d71c046e6.gif)

Here example with normal exposure and normal light setting. Still quite visible noise with big 'blobs' appearing and disappearing:
![sp3](https://user-images.githubusercontent.com/117785/80288842-0ed6cd80-873b-11ea-83f5-8af53c9430a9.gif)

I've played with Hysteresis and and change thresholds but only setting them to edge values like 0.99 helps a little bit at the cost of crazy slow rate of updates for scene changes.

My question, are there any options which would at cost of performance decrease size of those noise blobs? I think if they were smaller and more collocated it would be less distracting? 

I've tried to play with volume grid size but examples crash if i set it to bigger values. 

Any suggestions on how can i improve quality/stability of GI at cost of performance? What rules are driving max/valid size of volumes?

**Some additional info:**
- I'm using quite fresh master (last commit: 4c2c2c8cd04749bc8bceb9334592603e70b0f81a)
- RTX 2080 TI
- Windows 10 (18363.778)
- Nvidia Driver: 445.87

**Comment by acmarrs-nvidia** [comment]
Good questions. 

_Are there any options which would at cost of performance decrease size of those noise blobs? Any suggestions on how can i improve quality/stability of GI at cost of performance?_

Yes, higher image quality is possible by adjusting several knobs. The first is to increase the number of rays traced per probe (_DDGIVolumeDesc::numRaysPerProbe_). The more rays a probe traces, the more stable the lighting result will be. Along the same lines, increasing the number of probes in a volume and increasing the irradiance & distance texture resolutions will also help. Increasing the number of probes and texture resolutions will adjust how close the indirect lighting's "shape" is to the path tracer's result.

Probe Hysteresis is another way to stabilize the lighting result by emphasizing previous samples (in time). The tradeoff of this route, as you've noticed, is a lag in the lighting update. The trick is to find the balance that works for your lighting use case.

Also, remember that the lighting scenarios in Two Rooms and the Cornell Box are tough cases since the shaded surfaces (e.g. the walls you've highlighted) do not have high frequency materials (i.e. they don't have textures). The artifacts you are noticing won't be as evident (or visible at all) on surfaces with realistic materials and shading.

_I've tried to play with volume grid size but examples crash if i set it to bigger values. What rules are driving max/valid size of volumes?_

The maximum number of probes allowed in a volume is a function of 1) the maximum texture dimension in Direct3D (16384), and 2) the resolutions you've chosen for the probe irradiance and distance textures (_DDGIVolumeDesc::numIrradianceTexels_, _DDGIVolumeDesc::numDistanceTexels_)

**Comment by michax** [comment]
Thanks for detailed answer! Will play around with mentioned knobs.
