### ISSUE TITLE
irradiance.hlsl

### ISSUE THREAD

**Issue by zhuyuxiang1994** [NVIDIAGameWorks/RTXGI-DDGI#15]
In irradiance.hlsl line 185, irradiance *= (0.5 * RTXGI_PI);  //factored out of the probes

RTXGI_PI is lambert constant.However I can not figure out where is 0.5 come from.Is it a math constant or a code bug?

**Comment by acmarrs-nvidia** [comment]
Great question, @zhuyuxiang1994. This is indeed a bug, and has been fixed in [the latest code](https://github.com/NVIDIAGameWorks/RTXGI/releases/tag/1.1.2).

The irradiance (and distance) texels of the DDGI probes compute a Monte Carlo Estimate of irradiance.[ PBRT has a great overview of the math behind this](http://www.pbr-book.org/3ed-2018/Monte_Carlo_Integration/The_Monte_Carlo_Estimator.html). 

When blending irradiance (and distance) in `ProbeBlendingCS.hlsl`, we divide by the sum of the cosine weights (instead of the number of samples) to reduce variance while constructing the irradiance estimate. To correctly account for this change, [the cosine sum must be multiplied by 2](https://github.com/NVIDIAGameWorks/RTXGI/blob/ab3b2f398e2df7ba7838f3c04a2051a74d4d87ee/rtxgi-sdk/shaders/ddgi/ProbeBlendingCS.hlsl#L237). Since the the Monte Carlo summation is multiplied by the area of integration ([2PI in this case](https://github.com/NVIDIAGameWorks/RTXGI/blob/ab3b2f398e2df7ba7838f3c04a2051a74d4d87ee/rtxgi-sdk/shaders/ddgi/Irradiance.hlsl#L197)), we previously incorrectly cancelled out a term causing the incorrect division bv 2. 

 It is also possible to simply omit both multiplications by 2 from the latest code; however, we have left them in for clarity.
