### ISSUE TITLE
RtxGi not working

### ISSUE THREAD

**Issue by endyrare** [NVIDIAGameWorks/RTXGI-DDGI#17]
So I have everything set up correctly. I built the NvRtx branch from source and installed the patch and plugin and everything works right except the actual GI. 
![image](https://user-images.githubusercontent.com/70681990/92528395-b0485280-f1f6-11ea-8110-7e9d6332bd78.png)

Also when enabling ray traced shadows on the skylight the probes look transparent. 
![image](https://user-images.githubusercontent.com/70681990/92528474-d2da6b80-f1f6-11ea-9783-b99a58566a42.png)

**Comment by Atrix256** [comment]
Hi there!

A couple things could be going on with the GI.  The first thing I'd try is seeing "what the probes see" to make sure the sky is visible to raytracing, and that the raytraced scene isn't missing any geometry or similar.

You can do that by entering these two console commands:

1. r.RTXGI.DDGIProbeVis 1
2. vis ddgiprobevis

That will show you the world as the probes see it in a small window in the corner of the screen.  This screenshot as an example shows how it looks when the directional sky light is configured not to affect raytracing, which makes incorrect GI.

![image](https://user-images.githubusercontent.com/2304151/92531916-0e1f6f00-f1e4-11ea-8eda-2650e18eb5b8.png)

If nothing looks amiss there, If you have extended luminance enabled, or otherwise have large lighting values (maybe a strong tone mapper to bring them down to displayable levels), it could be hitting the limit of what is storable in the probes.  To fix that, you can try going into the project settings, under the RTXGI plugin section, and changing the Irradiance Bits to 32, to see if that helps the problem. If that does help, we are currently working on an alternate solution so that the smaller pixel format can be used with larger lighting values.

Let me know if either of those help.
Thanks!

**Comment by endyrare** [comment]
Hey thank you so much for the quick reply! After putting in the console
commands I don't see any small screen appearing to see what the probes see
[image: image.png]

 Even after switching the Irradiance to 32 bit nothing appears to change.

**Comment by MartianDays** [comment]
[removed my comment - I misread the above.]

**Comment by Atrix256** [comment]
If you aren't seeing a little window when you put in the commands, that could mean a couple things:
1. Raytracing is off in the project.  I'm talking about the "ray tracing" checkbox in the project settings.
2. A command was typod.  i copy/pasted what i typed just now to make sure it was correct, it was. Maybe try copy/pasting just to make sure?
3. As much as I hate to say it, it might need a clean re-build of code.
Could you try those things?

**Comment by Atrix256** [comment]
oh also, thanks for the report about the probes looking transparent!

**Comment by grgc25** [comment]
Hey @endyrare   I Found a fix. Kinda weird but yeah


Here´s the logic i followed:
1- use this command r.RTXGI.DDGIProbeVis 1
2- create a new level, the "time of day" level could do the trick
3-The geometry you had in your level, just copy it there.

That made me think there was something i added in the level that broke it.

I realized it´s the post processing volume.
Try adding one to your scene but uncheck the "unbound" option
Even probes work finew now

![Captura de pantalla (6)](https://user-images.githubusercontent.com/10503380/92555552-8e1df700-f22d-11ea-8222-74944256c63e.png)
![Captura de pantalla (7)](https://user-images.githubusercontent.com/10503380/92555559-90805100-f22d-11ea-83da-66a5a329782b.png)

**Comment by Atrix256** [comment]
Hey @grgc25 : that's weird that post processing was interfering with the GI.  Do you by chance have specific steps to cause this failure?

**Comment by grgc25** [comment]
> Hey @grgc25 : that's weird that post processing was interfering with the GI. Do you by chance have specific steps to cause this failure?

I set the post processing like i allways do,  just add it, unbound it, search "type" to get the raytracing effects, enable al of them. 2 bounces each, didnt matter which type of gi. 

Then, i made a quick blueprint to handle the ssgi switches, you know, show probes, vis probes, enable or disable and raytracing volumetric fog mode  (just so i didnt need to write each command everytime)

the prbe vis hides itself when inside the post processing.
maybe the probe rectangle is a post processing material in itself?

**Comment by Atrix256** [comment]
Oh ok... the issue with the post processing volume is that it's an either or situation. Next patch coming out will allow for eg SSGI and RTXGI working at the same time and adding to each other, but currently it's one or the other.

**Comment by animationdavid** [comment]
Same problem here, transparent light probes and the command for disable rtgi.ddgi to false it's not working:

![image](https://user-images.githubusercontent.com/50923753/92787391-576ceb80-f3a9-11ea-9e38-8ebe4817a77e.png)

I assume that I can use rtxgi with a Nvidia 1080Ti right?

**Comment by Atrix256** [comment]
Yeah a 1080Ti works with RTXGI.  If you can do raytracing in unreal, you can do RTXGI, no special requirements above that.
The probes looking transparent is a bug in them being rendered to the screen, but is safe to ignore as far as whether the probes are doing the right thing or not.
Try this... if you go into project settings, under the RTXGI plugin, and set the irradiance bits to 32, instead of 10, does that fix the problem?
Also worth noting: you can currently only use one type of GI at a time. So if you have SSGI on, RTXGI won't work.  The next patch makes it so they can work together.

**Comment by animationdavid** [comment]
I think I'm using 32 irradiance bits but let me check if SSGI it's on.

Thanks so much!

**Comment by animationdavid** [comment]
@Atrix256 Thanks! SSGI off and now works as expected:

![image](https://user-images.githubusercontent.com/50923753/92814452-70829600-f3c3-11ea-9e5b-38ccbc82798f.png)
![image](https://user-images.githubusercontent.com/50923753/92814468-7aa49480-f3c3-11ea-869c-f35d8aa08028.png)

**Comment by Atrix256** [comment]
Hooray! Glad to hear it's working :)
