### ISSUE TITLE
TestHarness Crashes On Launch

### ISSUE THREAD

**Issue by alextardif-zmi** [NVIDIAGameWorks/RTXGI-DDGI#2]
Was able to track this down to ParseApplication in Config.cpp, needed to remove the "- 1" from lines that are parsing: "line.size() - length - 1". Don't know if this is a configuration step I've missed that causes this, but doing this fixed it up and I was able to run everything just fine.

**Comment by acmarrs-nvidia** [comment]
I'm not able to reproduce this. Can you provide steps to repro?

**Comment by alextardif-zmi** [comment]
I just followed along the startup instructions in the readme, and built with VS 2019, debug x64. The app was crashing on launch when I ran it through the bat, so I debugged and it hit on this. The instructions for building were super clear/easy so I'm not sure what could account for this difference.

**Comment by acmarrs-nvidia** [comment]
It's odd the app crashed when run from the batch file. I can build a fresh clone with VS2019 and run the bat file without a problem. When it crashes after running from the bat, what is in the log file (samples/build/test-harness/log.txt)? Also, what version of Windows are you on?

**Comment by alextardif-zmi** [comment]
I see nothing in the log when it crashed, runs fine with those lines fixed though. Running on 17763.

I'm not sure how other people don't have this issue though, here's an example in ParseApplication for the "width" parameter:
//line is "width=1920"
//line.size() is 10
length = strlen("width=");
//length is 6
stoi(line.substr(strlen("width="), line.size() - length));
//equates to line.substr(6, 4);
//results in "1920"
//if - 1 was left in, results in "192"

**Comment by acmarrs-nvidia** [comment]
This is one of those annoyances that falls out of different line ending standards. Windows uses \r\n (two characters, carriage return then line feed). The code in Config.cpp expects this format since the target platform is Windows. It grabs lines delimited by \n, and then uses the -1 to account for the '\r' character.

So, for your example, "line" is actually "width=1920\r" which is 11 characters. For some reason, it appears your file .ini files do not have the \r\n characters at the end of the line. Perhaps a setting of your system or the tool you used to clone the repo?

**Comment by TheRealMJP** [comment]
I hit the same exact issue. I had grabbed the code by the just downloading the zip from GitHub, I didn't actually clone the repo.

**Comment by alextardif-zmi** [comment]
^ Also didn't clone the repo, straight downloaded the zip

**Comment by acmarrs-nvidia** [comment]
Ah! Interesting. Thanks for reporting this.

I downloaded the zip, and can reproduce what you are seeing. Looks like GitHub is losing the carriage return character when it prepares the zip package (probably because their machines are unix).

I'll make the config parsing more robust in a future update.

**Comment by Polyrhythm** [comment]
+1, with a Japanese locale I had to go through the bug fixing routine to get it to work

**Comment by acmarrs-nvidia** [comment]
This issue is now fixed. Please confirm, and I will close.

**Comment by alextardif-zmi** [comment]
Awesome, looks good, thanks!
