### ISSUE TITLE
Error after i enable the plugin

### ISSUE THREAD

**Issue by romeo615videos** [NVIDIAGameWorks/RTXGI-DDGI#22]
I get a error "The following modules are missing or built with a different engine version: RTXGI
Engine modules cannot be compiled at runtime. Please build through your IDE.

![image](https://user-images.githubusercontent.com/66187503/93685722-60cc1700-fa7f-11ea-8d4b-6f90015fc56e.png)

![image (1)](https://user-images.githubusercontent.com/66187503/93685764-ad175700-fa7f-11ea-8b38-53e9a41a11d7.png)
![image (2)](https://user-images.githubusercontent.com/66187503/93685786-c5877180-fa7f-11ea-9fc3-7a3af365ce2e.png)
![image (3)](https://user-images.githubusercontent.com/66187503/93685828-f49de300-fa7f-11ea-92a1-e9a1dffbd468.png)

**Comment by Atrix256** [comment]
Yeah, after applying the patch you need to build the engine because the patch applies a couple changes to the engine to be able to do what it does.

I see VS output saying it succeeded building, does that mean you were able to make it work after building the engine?

Specifically the steps are:
1. Apply the patch
2. Generate project files
3. Build the engine
4. Enable / use the plugin.

Let me know if that works for you, and looks like the docs could updated to be clearer on this...

Thanks!

**Comment by romeo615videos** [comment]
I will start working on it immediately and post the results. Really appreciate the response and guidance and I mean really really appreciate the guidance. You guys are doing great work for the community and we recognize all the hard work.

**Comment by romeo615videos** [comment]
The steps were just what i needed. Tested loading the plugin and engine. I was applying the patch at the last step. Rebuilding solved the issue. Thank you for the guidance and knowledge.

**Comment by Atrix256** [comment]
No problem, thanks for the kind words!
