### ISSUE TITLE
Can't see the probeVis

### ISSUE THREAD

**Issue by dpotuznik** [NVIDIAGameWorks/RTXGI-DDGI#25]
Hi,

first thank you for your amaizing job !.

i have an issue i can't see the Probe, i try on 2 project , 
i try to rebuild Unreal. (generate project file and rebuild)
but nothing seem to work.
i install the NVIDIA DLSS Unreal Engine and the RTXGI-NvRTX4.25.3.patch

![image](https://user-images.githubusercontent.com/11964995/97511912-78ed5b00-1988-11eb-88af-cc3ee13787b4.png)

thank you for your help.
Best Regards
Daniel

**Comment by Atrix256** [comment]
Hey there!
The plugin has 2 different debug visualizations.

One debug visualization shows the world from the camera's perspective as the probes see it.  This is to help diagnose problems caused by objects or lights not being visible to raytracing.
I see that debug visualization in your screenshot - the little window in the lower left shows the world as the probes see it.  They can see the emissive red box, and the directional light's direct lighting.

The other visualization lets you see the probes, which is what you are looking for.  You can see them with this command (image attached to show what they look like)
r.RTXGI.DDGIShowProbes 1

I'm closing this out but let me know if you have any other issues!


![image](https://user-images.githubusercontent.com/2304151/97604148-6c89f200-19ca-11eb-88bf-594c1ec00929.png)
