### ISSUE TITLE
How to handle rect area light with RTXGI

### ISSUE THREAD

**Issue by SSKK-jiajun-zhang** [NVIDIAGameWorks/RTXGI-DDGI#43]
Hello!

In order to calculate probe irradiance, RTXGI requires to calculate direct diffuse from lights first. And the "TestHarness" project has shown how to handle direct diffuse calculation of directional, point and spot light but without area light. What is the proper way to integrate area light into RTXGI SDK? 
(especially its partial visibility problem, as "TestHarness" can just use one visibility ray for punctual lights but this doesn't work with area light)

I notice that the paper "Dynamic Diffuse Global Illumination with Ray-Traced Irradiance Fields" that RTXGI based on has such a statement:

> We can also handle direct illumination from extended area light sources using our indirect illumination pipeline: all one-bounce indirect lighting contributions compute one bounce of lighting seeded by the direct illumination in a scene. Multiple bounces of indirect illumination are instead seeded by the previous bounce of indirect lighting in the scene. With this in mind, we can compute direct illumination from area lighting by seeding our indirect illumination shading routine with the area lighting emission profile in the scene (i.e., instead of the direct illumination profile)

Is it possible to elaborate the "area lighting emission profile" here?

**Comment by acmarrs-nvidia** [comment]
Hi @svart-jiajunzhang - apologies for the long delay. Due to the low resolution nature of how irradiance is stored in the DDGI probes, you can get away with applying an emissive material to geometry to "automatically" support area lights. In other words, you don't need to explicitly evaluate direct lighting for area light sources at probe ray hits since DDGI probes treat _all_ surfaces as potential sources of light. Simply determine the visibility to the emissive surface's hit location and (if visible) evaluate its BSDF to compute incoming radiance as you do with non-emissive surfaces.
