### ISSUE TITLE
Discontinuities in lit surface

### ISSUE THREAD

**Issue by tomdrinKEENSWH** [NVIDIAGameWorks/RTXGI-DDGI#48]
Hello,
I would like to ask about artifacts I'm getting. Sphere is close to the wall, is not moving. The directional light is also not moving.
One patch of the wall in proximity of the sphere is black - completely unlit. I understand the nearest light probes are shadowed by the sphere. But I would expect that the pixel would be illuminated by several probes and therefore produce continuous result.  

![rtxgi_artefact_01](https://user-images.githubusercontent.com/79200426/112643823-115b0f00-8e45-11eb-83de-ef5ad9df8b17.png)

Is it a bug or feature? How to reduce this effect?

Thanks a lot in advance
Tomas Drinovsky

**Comment by tiont** [comment]
Hi @tomdrinKEENSWH . As this issue was original reported back in March, we've had quite a few updates to the RTXGI plugin since then. I would ask if you can please download the latest version (v.1.1.42) from [here ](https://developer.nvidia.com/rtxgi-sdk-get-started#ue4-latest-version )and report if you are still seeing this same issue. Thanks and apologies for the delayed response
