### ISSUE TITLE
D3D12 barriers prevent usage on compute command lists

### ISSUE THREAD

**Issue by Silveryard** [NVIDIAGameWorks/RTXGI-DDGI#68]
rtxgi::d3d12::UpdateDDGIVolumeProbes transitions resources from D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE to D3D12_RESOURCE_STATE_UNORDERED_ACCESS at the beginning and back at the end.

The problem is barriers involving D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE can only be done in direct command lists and not in compute command lists and trying to do so will trigger the following debug validation message:

`DX ERROR: ID3D12CommandList::ResourceBarrier: D3D12_RESOURCE_STATES has invalid flags for compute command list. [ RESOURCE_MANIPULATION ERROR #537: ]`

Being able to specify initial (and final) resource states for methods involving transition barriers would provide additional flexibility here.

**Comment by acmarrs-nvidia** [comment]
Hi @Silveryard - thanks for the feedback. I've made some adjustments to the SDK and Test Harness to address this problem and they will be included in the next release. 

Instead of resource transitions being configurable in ```UpdateDDGIVolumeProbes()```, I've opted to remove the transitions from the function (UAV barriers are still there of course). Instead, ```DDGIVolume``` resources can be transitioned to the appropriate states with a new function: ```DDGIVolume::TransitionResources(ID3D12GraphicsCommandList* cmdList, EDDGIExecutionStage stage)```. 

So, ```DDGIVolume``` resources will have the following states:
- Ray Data is always ```D3D12_RESOURCE_STATE_UNORDERED_ACCESS```
- Irradiance, Distance, and Probe Data:
  - Start as ```D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE```
  - Transition to ```D3D12_RESOURCE_STATE_UNORDERED_ACCESS``` after probe tracing is complete and before ```UpdateDDGIVolumeProbes()```, ```RelocateDDGIVolumeProbes()```, and ```ClassifyDDGIVolumeProbes()``` execute
  - Transition back to ```D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE``` when using ***compute shaders*** to gather indirect light
  - Transition to ```D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE``` when using ***pixel shaders*** to gather indirect light and then finally back to ```D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE``` once the pixel shader gather is complete
