### ISSUE TITLE
Test-harness crashing

### ISSUE THREAD

**Issue by gamehacker1999** [NVIDIAGameWorks/RTXGI-DDGI#7]
I am trying to run the test harness sample on visual studio however it just crashes when I launch it. I opened the log.txt file and the error says "Failed to initialize D3D12", which is very weird since I have been working with DX12 and DXR for a couple of months now with no issues. I just followed the instructions from the doc on how to build it. I am using VS2019. Any ideas on what might be causing this?

**Comment by pixnblox** [comment]
Can you try my fork to see if that helps? https://github.com/pixnblox/RTXGI There is an open issue (and pull request) for that: https://github.com/NVIDIAGameWorks/RTXGI/issues/3.

**Comment by acmarrs-nvidia** [comment]
@gamehacker1999 - did you download the zip instead of cloning the repo? When you download the zip, GitHub changes the line endings of the configuration files. This makes the parser fail. There is an open issue related to this, and a fix will be pushed soon. In the meantime you can clone the repo and things should work fine. 

If you are having this issue after cloning the repo, then I recommend dropping a breakpoint in the D3D12::Initialize() function and step until you find the failure. If the failure doesn't make sense, or you think it is wrong, respond here and let me know what's happening.

**Comment by LaurentGarcia** [comment]
To me I am getting the same error if I try to execute it standalone. If I run the application with VS runs without an issue.

**Comment by acmarrs-nvidia** [comment]
@LaurentGarcia, are you running the executable directly (i.e. without the required command line arguments)? Does the application run properly when you run the "runTestHarness.bat" file?

The latest code now spawns a message box to give you a better idea of what's going wrong.

**Comment by acmarrs-nvidia** [comment]
Closing for lack of response. Reopen if you are still having issues.
